echo === INICIANDO PROGRAMA ===
echo P1 9
echo P2 8
echo P3 7
echo Compilando...
gcc -w -o teste main.c gera.c
echo Executando teste 1...
./teste teste.txt
echo Executando teste 2...
./teste teste2.txt
echo Executando teste 3...
./teste teste3.txt
echo === FIM DO PROGRAMA ===
